---
- name: Add a user on Ubuntu and CentOS instances
  hosts: localhost
  gather_facts: yes
  become: yes
  become_user: yes
  become_method: sudo
  tasks: 
  - name: Add a user
    user:
      name: "John"
      password: "{{ lookup('cypher', 'secret=secret/userpass') | password_hash('sha512') }}"
      state: present
